### ISSUE TITLE
release v0.2.0

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/memozo#32]
# TODO
- [ ] #8 add logger function
- [ ] #18 write example in each methods
- [ ] #30 add sphinx docs 
- [ ] #6  add appropriate arguments to methods (analogous to each file operator (e.g., open, codecs, ...))
